ARG WINDOWS_VERSION="1809"

# The files in this image are copied to $env:CONTAINER_SANDBOX_MOUNT_POINT on the host.
FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

ENV PATH="C:\Program Files\PowerShell;C:\utils;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;"

COPY  ebpf-win-temp-e56e80.zip /ebpf-win-temp.zip
COPY  entrypoint.ps1 /

# The nanoserver image does not have powershell but this works because
# this container will be running on the host.
ENTRYPOINT ["powershell"]
