# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

ARG WINDOWS_VERSION="1809"

# The files in this image are copied to $env:CONTAINER_SANDBOX_MOUNT_POINT on the host.
FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

ENV PATH="C:\Program Files\PowerShell;C:\utils;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;"

COPY  capz-preinstall.ps1 /
COPY  hns.psm1 /

ENTRYPOINT ["powershell"]
